name: launch_sdk
description: "Platform Launcher and Orchestration SDK"
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.5"
dependencies:
  flutter:
    sdk: flutter
  core_sdk:
    path: ../core_sdk
  auth_sdk:
    path: ../auth_sdk
  users_sdk:
    path: ../users_sdk
  comms_sdk:
    path: ../comms_sdk
  productivity_sdk:
    path: ../productivity_sdk
  flutter_riverpod: ^2.4.9
  installed_apps: ^2.1.1
  remixicon: ^4.9.3
