name: desktop_sdk
description: "Custom native desktop runners (windows, macos, linux) and desktop configurations for RokctApp."
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"
dependencies:
  flutter:
    sdk: flutter

dependency_overrides:
  http: ^1.2.0
