name: wallet_sdk
description: "Wallet Balances and Transaction Ledgers SDK"
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.5"
dependencies:
  flutter:
    sdk: flutter
  core_sdk:
    path: ../core_sdk
