name: delivery_sdk
description: "Courier, parcel shipping, and driver location SDK for RokctApp."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter
  core_sdk:
    path: ../core_sdk
  map_sdk:
    path: ../map_sdk

  dartz: ^0.10.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.10.4

flutter:
