name: weather_sdk
description: A new Flutter package for weather_sdk.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  core_sdk:
    path: ../core_sdk

dependency_overrides:
  http: ^1.2.0
