///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  // --- Audio ---
  static const String audioNotification = 'assets/audio/notification.wav';

  // --- Images ---
  static const String imageAppLogo = 'assets/image/app_logo.png';
  static const String imageBackground = 'assets/image/background.png';
  static const String imageDelivery = 'assets/image/delivery.png';
  static const String imageLunch = 'assets/image/lunch.png';
  static const String imageManager = 'assets/image/manager.png';
  static const String imageMarker = 'assets/image/marker.png';
  static const String imageMyLocation = 'assets/image/my_location.png';
  static const String imageNoNotification = 'assets/image/noNotification.png';
  static const String imageNoOrders = 'assets/image/no_orders.png';
  static const String imageNoProduct = 'assets/image/noProduct.png';
  static const String imageQr = 'assets/image/qr.png';
  static const String imageDoor = 'assets/image/door.png';
  static const String imageDoorToDoor3 = 'assets/image/door_to_door_3.png';
  static const String imageFast = 'assets/image/fast.png';
  static const String imageLogo = 'assets/image/logo.png';
  static const String imageMapMarker = 'assets/image/map_marker.bmp';
  static const String imageNotFound = 'assets/image/notFound.png';
  static const String imagePerson = 'assets/image/person.png';
  static const String imageSplash = 'assets/image/splash.png';
  static const String imageSave = 'assets/image/save.png';
  static const String imageSet = 'assets/image/set.png';
  static const String imageSplash1 = 'assets/image/splash1.png';
  static const String imageUi0 = 'assets/image/ui0.png';
  static const String imageUi1 = 'assets/image/ui1.png';
  static const String imageUi2 = 'assets/image/ui2.png';
  static const String imageUi3 = 'assets/image/ui3.png';
  static const String imageUserMarker = 'assets/image/user_marker.png';
  static const String imageVisa = 'assets/image/visa.png';

  // --- Lottie ---
  static const String lottieClose = 'assets/lottie/close.json';
  static const String lottieEmptyBox = 'assets/lottie/empty-box.json';
  static const String lottieGirlEmpty = 'assets/lottie/girl_empty.json';
  static const String lottieNotFound = 'assets/lottie/not-found.json';
  static const String lottieNotFoundPage = 'assets/lottie/not_found_page.json';
  static const String lottiePin = 'assets/lottie/pin.json';
  static const String lottieProcessing = 'assets/lottie/processing.json';

  // --- SVG ---
  static const String svgBalance = 'assets/svg/balance.svg';
  static const String svgDelivery = 'assets/svg/delivery.svg';
  static const String svgFoodyman = 'assets/svg/foodyman.svg';
  static const String svgHome = 'assets/svg/home.svg';
  static const String svgLogoWhite = 'assets/svg/logoWhite.svg';
  static const String svgMenu = 'assets/svg/menu.svg';
  static const String svgMyLocation = 'assets/svg/my_location.svg';
  static const String svgNoHome = 'assets/svg/noHome.svg';
  static const String svgAddress = 'assets/svg/adress.svg';
  static const String svgAvatar = 'assets/svg/avatar.svg';
  static const String svgBadge = 'assets/svg/badge.svg';
  static const String svgBag2 = 'assets/svg/bag2.svg';
  static const String svgBag3 = 'assets/svg/bag3.svg';
  static const String svgBox = 'assets/svg/box.svg';
  static const String svgCategory2 = 'assets/svg/category2.svg';
  static const String svgCategory3 = 'assets/svg/category3.svg';
  static const String svgContact = 'assets/svg/contact.svg';
  static const String svgDelivery0 = 'assets/svg/delivery0.svg';
  static const String svgDelivery2 = 'assets/svg/delivery2.svg';
  static const String svgDeliveryTime = 'assets/svg/delivery_time.svg';
  static const String svgDiscount = 'assets/svg/discount.svg';
  static const String svgEmpty = 'assets/svg/empty.svg';
  static const String svgFilter = 'assets/svg/filter.svg';
  static const String svgFosend2 = 'assets/svg/fosend2.svg';
  static const String svgFosend3 = 'assets/svg/fosend3.svg';
  static const String svgHalal = 'assets/svg/halal.svg';
  static const String svgHome3 = 'assets/svg/home3.svg';
  static const String svgHomeSvg = 'assets/svg/homeSvg.svg';
  static const String svgLikeSvg = 'assets/svg/likeSvg.svg';
  static const String svgLogo = 'assets/svg/logo.svg';
  static const String svgMeat = 'assets/svg/meat.svg';
  static const String svgNoHomeSvg = 'assets/svg/noHomeSvg.svg';
  static const String svgNoLikeSvg = 'assets/svg/noLikeSvg.svg';
  static const String svgNoSearchSvg = 'assets/svg/noSearchSvg.svg';
  static const String svgOrderTime = 'assets/svg/orderTime.svg';
  static const String svgPickUpFrom = 'assets/svg/pickUpFrom.svg';
  static const String svgSearchSvg = 'assets/svg/searchSvg.svg';
  static const String svgStar = 'assets/svg/star.svg';
  static const String svgTicket = 'assets/svg/ticket.svg';
  static const String svgVegetarian = 'assets/svg/vegetarin.svg';
}