name: promotions_sdk
description: Promotions SDK for banners, coupons, and stories.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.5"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_riverpod: ^2.6.1
  drift: ^2.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.19.0
  build_runner: ^2.4.9
