name: comms_sdk
description: "Real-time communication, chat messaging, and FCM push notifications SDK for RokctApp."
version: 1.0.0
homepage:

environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter
  core_sdk:
    git:
      url: https://github.com/RokctAI/flutter_sdk.git
      path: sdk/core_sdk
      ref: ^1.0.0
  firebase_messaging: ^16.1.0
  dartz: ^0.10.1
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.10.4

flutter:
