name: hardware_sdk
description: "Unified hardware peripheral interface package for RokctApp."
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  print_bluetooth_thermal: any
  flutter_riverpod: ^2.6.1
  permission_handler: ^12.0.1
  mobile_scanner: ^6.0.4
  shared_preferences: ^2.5.4
  freezed_annotation: ^3.1.0
  rxdart: any
  network_info_plus: any
  ping_discover_network_forked: any
  flutter_pos_printer_platform_image_3: any
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  freezed: any
  build_runner: ^2.4.8

dependency_overrides:
  http: ^1.2.0
