name: fav_sdk
description: A generic and reusable favorites/bookmarking engine.
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: '>=3.38.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  get_it: ^9.2.0
  core_sdk:
    git:
      url: https://github.com/RokctAI/flutter_sdk.git
      path: sdk/core_sdk
      ref: ^1.0.0
