name: core_sdk
description: "Common utilities, shared models (Translation, Location), storage, and network foundation."
version: 1.0.0
publish_to: 'none'
environment:
  sdk: '>=3.10.0 <4.0.0'
  flutter: ">=3.38.5"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
dev_dependencies:
  build_runner: ^2.15.0
  drift: ^2.34.0
  drift_dev: ^2.34.0
  flutter_riverpod: ^2.6.1
  internet_connection_checker_plus: ^3.1.0
  path: ^1.9.1
  path_provider: ^2.1.6
  sqlite3_flutter_libs: ^0.6.0+eol
  uuid: ^4.5.3
